import 'dart:io';
import 'dart:math';
import 'dart:convert';

import 'package:flutter/material.dart';

import 'package:path_provider/path_provider.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:platypus/providers/home.dart';

// https://github.com/pd4d10/highlight/tree/master/highlight/lib/languages
const List<String> _programmingLanguages = [
  '1c',
  'abnf',
  'accesslog',
  'actionscript',
  'ada',
  'all',
  'angelscript',
  'apache',
  'applescript',
  'arcade',
  'arduino',
  'armasm',
  'asciidoc',
  'aspectj',
  'autohotkey',
  'autoit',
  'avrasm',
  'awk',
  'axapta',
  'bash',
  'basic',
  'bnf',
  'brainfuck',
  'cal',
  'capnproto',
  'ceylon',
  'clean',
  'clojure-repl',
  'clojure',
  'cmake',
  'coffeescript',
  'coq',
  'cos',
  'cpp',
  'crmsh',
  'crystal',
  'cs',
  'csp',
  'css',
  'd',
  'dart',
  'delphi',
  'diff',
  'django',
  'dns',
  'dockerfile',
  'dos',
  'dsconfig',
  'dts',
  'dust',
  'ebnf',
  'elixir',
  'elm',
  'erb',
  'erlang-repl',
  'erlang',
  'excel',
  'fix',
  'flix',
  'fortran',
  'fsharp',
  'gams',
  'gauss',
  'gcode',
  'gherkin',
  'glsl',
  'gml',
  'gn',
  'go',
  'golo',
  'gradle',
  'graphql',
  'groovy',
  'haml',
  'handlebars',
  'haskell',
  'haxe',
  'hsp',
  'htmlbars',
  'http',
  'hy',
  'inform7',
  'ini',
  'irpf90',
  'isbl',
  'java',
  'javascript',
  'jboss-cli',
  'json',
  'julia-repl',
  'julia',
  'kotlin',
  'lasso',
  'ldif',
  'leaf',
  'less',
  'lisp',
  'livecodeserver',
  'livescript',
  'llvm',
  'lsl',
  'lua',
  'makefile',
  'markdown',
  'mathematica',
  'matlab',
  'maxima',
  'mel',
  'mercury',
  'mipsasm',
  'mizar',
  'mojolicious',
  'monkey',
  'moonscript',
  'n1ql',
  'nginx',
  'nimrod',
  'nix',
  'nsis',
  'objectivec',
  'ocaml',
  'openscad',
  'oxygene',
  'parser3',
  'perl',
  'pf',
  'pgsql',
  'php',
  'plaintext',
  'pony',
  'powershell',
  'processing',
  'profile',
  'prolog',
  'properties',
  'protobuf',
  'puppet',
  'purebasic',
  'python',
  'q',
  'qml',
  'r',
  'reasonml',
  'rib',
  'roboconf',
  'routeros',
  'rsl',
  'ruby',
  'ruleslanguage',
  'rust',
  'sas',
  'scala',
  'scheme',
  'scilab',
  'scss',
  'shell',
  'smali',
  'smalltalk',
  'sml',
  'solidity',
  'sqf',
  'sql',
  'stan',
  'stata',
  'step21',
  'stylus',
  'subunit',
  'swift',
  'taggerscript',
  'tap',
  'tcl',
  'tex',
  'thrift',
  'tp',
  'twig',
  'typescript',
  'vala',
  'vbnet',
  'vbscript-html',
  'vbscript',
  'verilog',
  'vhdl',
  'vim',
  'vue',
  'x86asm',
  'xl',
  'xml',
  'xquery',
  'yaml',
  'zephir',
];

final Map<String, String> programmingLanguages = {
  ...Map.fromEntries(_programmingLanguages.map((programmingLanguage) =>
      MapEntry(programmingLanguage, programmingLanguage))),
};

enum WindowThreeCirclesStyle {
  Filled,
  Empty,
  Hidden,
}

const Map<String, MainAxisAlignment> windowThreeCirclesPositions = {
  'Left': MainAxisAlignment.start,
  'Center': MainAxisAlignment.center,
  'Right': MainAxisAlignment.end,
};

// https://www.nbdtech.com/Blog/archive/2008/04/27/Calculating-the-Perceived-Brightness-of-a-Color.aspx
Color getCircleColor(Color c) {
  return sqrt(c.red * c.red * .241 +
              c.green * c.green * .691 +
              c.blue * c.blue * .068) <
          130
      ? Colors.white
      : Colors.black;
}

Future exportCurrentPlatypusConfig(HomeProvider homeProvider) async {
  final Directory downloadPath = await getApplicationDocumentsDirectory();
  final File configFile = File(
      '${downloadPath.path}/platypus-config-${DateTime.now().toString()}.json');
  final Map<String, dynamic> config = {
    'horizontal_padding':
        homeProvider.horizontalPaddingBetweenCodeAndBackground,
    'vertical_padding': homeProvider.verticalPaddingBetweenCodeAndBackground,
    'font_size': homeProvider.codeFontSize,
    'window_circles_style': homeProvider.windowThreeCirclesStyle,
    'window_circles_position': homeProvider.windowThreeCirclesPosition,
    'highlight_theme': homeProvider.codeHighlightTheme,
    'line_height': homeProvider.codeLineHeight,
    'show_shadow': homeProvider.showShadow,
    'programming_language': homeProvider.codeProgrammingLanguage,
    'source_code': homeProvider.codeTextEditingController.text,
    'background_color': homeProvider.codeBackgroundColor.value,
  };
  final generatedConfigFile =
      await configFile.writeAsString(jsonEncode(config));
  return generatedConfigFile;
}

final Map<String, TextStyle> extractedGoogleFonts = {
  'aBeeZee': GoogleFonts.aBeeZee(),
  'abel': GoogleFonts.abel(),
  'abhayaLibre': GoogleFonts.abhayaLibre(),
  'abrilFatface': GoogleFonts.abrilFatface(),
  'aclonica': GoogleFonts.aclonica(),
  'acme': GoogleFonts.acme(),
  'actor': GoogleFonts.actor(),
  'adamina': GoogleFonts.adamina(),
  'adventPro': GoogleFonts.adventPro(),
  'aguafinaScript': GoogleFonts.aguafinaScript(),
  'akronim': GoogleFonts.akronim(),
  'aladin': GoogleFonts.aladin(),
  'alata': GoogleFonts.alata(),
  'alatsi': GoogleFonts.alatsi(),
  'aldrich': GoogleFonts.aldrich(),
  'alef': GoogleFonts.alef(),
  'alegreya': GoogleFonts.alegreya(),
  'alegreyaSC': GoogleFonts.alegreyaSC(),
  'alegreyaSans': GoogleFonts.alegreyaSans(),
  'alegreyaSansSC': GoogleFonts.alegreyaSansSC(),
  'aleo': GoogleFonts.aleo(),
  'alexBrush': GoogleFonts.alexBrush(),
  'alfaSlabOne': GoogleFonts.alfaSlabOne(),
  'alice': GoogleFonts.alice(),
  'alike': GoogleFonts.alike(),
  'alikeAngular': GoogleFonts.alikeAngular(),
  'allan': GoogleFonts.allan(),
  'allerta': GoogleFonts.allerta(),
  'allertaStencil': GoogleFonts.allertaStencil(),
  'allura': GoogleFonts.allura(),
  'almarai': GoogleFonts.almarai(),
  'almendra': GoogleFonts.almendra(),
  'almendraDisplay': GoogleFonts.almendraDisplay(),
  'almendraSC': GoogleFonts.almendraSC(),
  'amarante': GoogleFonts.amarante(),
  'amaranth': GoogleFonts.amaranth(),
  'amaticSC': GoogleFonts.amaticSC(),
  'amethysta': GoogleFonts.amethysta(),
  'amiko': GoogleFonts.amiko(),
  'amiri': GoogleFonts.amiri(),
  'amita': GoogleFonts.amita(),
  'anaheim': GoogleFonts.anaheim(),
  'andada': GoogleFonts.andada(),
  'andika': GoogleFonts.andika(),
  'angkor': GoogleFonts.angkor(),
  'annieUseYourTelescope': GoogleFonts.annieUseYourTelescope(),
  'anonymousPro': GoogleFonts.anonymousPro(),
  'antic': GoogleFonts.antic(),
  'anticDidone': GoogleFonts.anticDidone(),
  'anticSlab': GoogleFonts.anticSlab(),
  'anton': GoogleFonts.anton(),
  'arapey': GoogleFonts.arapey(),
  'arbutus': GoogleFonts.arbutus(),
  'arbutusSlab': GoogleFonts.arbutusSlab(),
  'architectsDaughter': GoogleFonts.architectsDaughter(),
  'archivo': GoogleFonts.archivo(),
  'archivoBlack': GoogleFonts.archivoBlack(),
  'archivoNarrow': GoogleFonts.archivoNarrow(),
  'arefRuqaa': GoogleFonts.arefRuqaa(),
  'arimaMadurai': GoogleFonts.arimaMadurai(),
  'arimo': GoogleFonts.arimo(),
  'arizonia': GoogleFonts.arizonia(),
  'armata': GoogleFonts.armata(),
  'arsenal': GoogleFonts.arsenal(),
  'artifika': GoogleFonts.artifika(),
  'arvo': GoogleFonts.arvo(),
  'arya': GoogleFonts.arya(),
  'asap': GoogleFonts.asap(),
  'asapCondensed': GoogleFonts.asapCondensed(),
  'asar': GoogleFonts.asar(),
  'asset': GoogleFonts.asset(),
  'assistant': GoogleFonts.assistant(),
  'astloch': GoogleFonts.astloch(),
  'asul': GoogleFonts.asul(),
  'athiti': GoogleFonts.athiti(),
  'atma': GoogleFonts.atma(),
  'atomicAge': GoogleFonts.atomicAge(),
  'aubrey': GoogleFonts.aubrey(),
  'audiowide': GoogleFonts.audiowide(),
  'autourOne': GoogleFonts.autourOne(),
  'average': GoogleFonts.average(),
  'averageSans': GoogleFonts.averageSans(),
  'averiaGruesaLibre': GoogleFonts.averiaGruesaLibre(),
  'averiaLibre': GoogleFonts.averiaLibre(),
  'averiaSansLibre': GoogleFonts.averiaSansLibre(),
  'averiaSerifLibre': GoogleFonts.averiaSerifLibre(),
  'b612': GoogleFonts.b612(),
  'b612Mono': GoogleFonts.b612Mono(),
  'badScript': GoogleFonts.badScript(),
  'bahiana': GoogleFonts.bahiana(),
  'bahianita': GoogleFonts.bahianita(),
  'baiJamjuree': GoogleFonts.baiJamjuree(),
  'baloo': GoogleFonts.baloo(),
  'balooBhai': GoogleFonts.balooBhai(),
  'balooBhaijaan': GoogleFonts.balooBhaijaan(),
  'balooBhaina': GoogleFonts.balooBhaina(),
  'balooChettan': GoogleFonts.balooChettan(),
  'balooDa': GoogleFonts.balooDa(),
  'balooPaaji': GoogleFonts.balooPaaji(),
  'balooTamma': GoogleFonts.balooTamma(),
  'balooTammudu': GoogleFonts.balooTammudu(),
  'balooThambi': GoogleFonts.balooThambi(),
  'balthazar': GoogleFonts.balthazar(),
  'bangers': GoogleFonts.bangers(),
  'barlow': GoogleFonts.barlow(),
  'barlowCondensed': GoogleFonts.barlowCondensed(),
  'barlowSemiCondensed': GoogleFonts.barlowSemiCondensed(),
  'barriecito': GoogleFonts.barriecito(),
  'barrio': GoogleFonts.barrio(),
  'basic': GoogleFonts.basic(),
  'baskervville': GoogleFonts.baskervville(),
  'battambang': GoogleFonts.battambang(),
  'baumans': GoogleFonts.baumans(),
  'bayon': GoogleFonts.bayon(),
  'beVietnam': GoogleFonts.beVietnam(),
  'bebasNeue': GoogleFonts.bebasNeue(),
  'belgrano': GoogleFonts.belgrano(),
  'bellefair': GoogleFonts.bellefair(),
  'belleza': GoogleFonts.belleza(),
  'benchNine': GoogleFonts.benchNine(),
  'bentham': GoogleFonts.bentham(),
  'berkshireSwash': GoogleFonts.berkshireSwash(),
  'bethEllen': GoogleFonts.bethEllen(),
  'bevan': GoogleFonts.bevan(),
  'bigShouldersDisplay': GoogleFonts.bigShouldersDisplay(),
  'bigShouldersText': GoogleFonts.bigShouldersText(),
  'bigelowRules': GoogleFonts.bigelowRules(),
  'bigshotOne': GoogleFonts.bigshotOne(),
  'bilbo': GoogleFonts.bilbo(),
  'bilboSwashCaps': GoogleFonts.bilboSwashCaps(),
  'bioRhyme': GoogleFonts.bioRhyme(),
  'bioRhymeExpanded': GoogleFonts.bioRhymeExpanded(),
  'biryani': GoogleFonts.biryani(),
  'bitter': GoogleFonts.bitter(),
  'blackAndWhitePicture': GoogleFonts.blackAndWhitePicture(),
  'blackHanSans': GoogleFonts.blackHanSans(),
  'blackOpsOne': GoogleFonts.blackOpsOne(),
  'blinker': GoogleFonts.blinker(),
  'bokor': GoogleFonts.bokor(),
  'bonbon': GoogleFonts.bonbon(),
  'boogaloo': GoogleFonts.boogaloo(),
  'bowlbyOne': GoogleFonts.bowlbyOne(),
  'bowlbyOneSC': GoogleFonts.bowlbyOneSC(),
  'brawler': GoogleFonts.brawler(),
  'breeSerif': GoogleFonts.breeSerif(),
  'bubblegumSans': GoogleFonts.bubblegumSans(),
  'bubblerOne': GoogleFonts.bubblerOne(),
  'buda': GoogleFonts.buda(),
  'buenard': GoogleFonts.buenard(),
  'bungee': GoogleFonts.bungee(),
  'bungeeHairline': GoogleFonts.bungeeHairline(),
  'bungeeInline': GoogleFonts.bungeeInline(),
  'bungeeOutline': GoogleFonts.bungeeOutline(),
  'bungeeShade': GoogleFonts.bungeeShade(),
  'butcherman': GoogleFonts.butcherman(),
  'butterflyKids': GoogleFonts.butterflyKids(),
  'cabin': GoogleFonts.cabin(),
  'cabinCondensed': GoogleFonts.cabinCondensed(),
  'cabinSketch': GoogleFonts.cabinSketch(),
  'caesarDressing': GoogleFonts.caesarDressing(),
  'cagliostro': GoogleFonts.cagliostro(),
  'cairo': GoogleFonts.cairo(),
  'calistoga': GoogleFonts.calistoga(),
  'calligraffitti': GoogleFonts.calligraffitti(),
  'cambay': GoogleFonts.cambay(),
  'cambo': GoogleFonts.cambo(),
  'candal': GoogleFonts.candal(),
  'cantarell': GoogleFonts.cantarell(),
  'cantataOne': GoogleFonts.cantataOne(),
  'cantoraOne': GoogleFonts.cantoraOne(),
  'capriola': GoogleFonts.capriola(),
  'cardo': GoogleFonts.cardo(),
  'carme': GoogleFonts.carme(),
  'carroisGothic': GoogleFonts.carroisGothic(),
  'carroisGothicSC': GoogleFonts.carroisGothicSC(),
  'carterOne': GoogleFonts.carterOne(),
  'catamaran': GoogleFonts.catamaran(),
  'caudex': GoogleFonts.caudex(),
  'caveat': GoogleFonts.caveat(),
  'caveatBrush': GoogleFonts.caveatBrush(),
  'cedarvilleCursive': GoogleFonts.cedarvilleCursive(),
  'cevicheOne': GoogleFonts.cevicheOne(),
  'chakraPetch': GoogleFonts.chakraPetch(),
  'changa': GoogleFonts.changa(),
  'changaOne': GoogleFonts.changaOne(),
  'chango': GoogleFonts.chango(),
  'charm': GoogleFonts.charm(),
  'charmonman': GoogleFonts.charmonman(),
  'chathura': GoogleFonts.chathura(),
  'chauPhilomeneOne': GoogleFonts.chauPhilomeneOne(),
  'chelaOne': GoogleFonts.chelaOne(),
  'chelseaMarket': GoogleFonts.chelseaMarket(),
  'chenla': GoogleFonts.chenla(),
  'cherryCreamSoda': GoogleFonts.cherryCreamSoda(),
  'cherrySwash': GoogleFonts.cherrySwash(),
  'chewy': GoogleFonts.chewy(),
  'chicle': GoogleFonts.chicle(),
  'chilanka': GoogleFonts.chilanka(),
  'chivo': GoogleFonts.chivo(),
  'chonburi': GoogleFonts.chonburi(),
  'cinzel': GoogleFonts.cinzel(),
  'cinzelDecorative': GoogleFonts.cinzelDecorative(),
  'clickerScript': GoogleFonts.clickerScript(),
  'coda': GoogleFonts.coda(),
  'codaCaption': GoogleFonts.codaCaption(),
  'codystar': GoogleFonts.codystar(),
  'coiny': GoogleFonts.coiny(),
  'combo': GoogleFonts.combo(),
  'comfortaa': GoogleFonts.comfortaa(),
  'comingSoon': GoogleFonts.comingSoon(),
  'concertOne': GoogleFonts.concertOne(),
  'condiment': GoogleFonts.condiment(),
  'content': GoogleFonts.content(),
  'contrailOne': GoogleFonts.contrailOne(),
  'convergence': GoogleFonts.convergence(),
  'cookie': GoogleFonts.cookie(),
  'copse': GoogleFonts.copse(),
  'corben': GoogleFonts.corben(),
  'cormorant': GoogleFonts.cormorant(),
  'cormorantGaramond': GoogleFonts.cormorantGaramond(),
  'cormorantInfant': GoogleFonts.cormorantInfant(),
  'cormorantSC': GoogleFonts.cormorantSC(),
  'cormorantUnicase': GoogleFonts.cormorantUnicase(),
  'cormorantUpright': GoogleFonts.cormorantUpright(),
  'courgette': GoogleFonts.courgette(),
  'courierPrime': GoogleFonts.courierPrime(),
  'cousine': GoogleFonts.cousine(),
  'coustard': GoogleFonts.coustard(),
  'coveredByYourGrace': GoogleFonts.coveredByYourGrace(),
  'craftyGirls': GoogleFonts.craftyGirls(),
  'creepster': GoogleFonts.creepster(),
  'creteRound': GoogleFonts.creteRound(),
  'crimsonPro': GoogleFonts.crimsonPro(),
  'crimsonText': GoogleFonts.crimsonText(),
  'croissantOne': GoogleFonts.croissantOne(),
  'crushed': GoogleFonts.crushed(),
  'cuprum': GoogleFonts.cuprum(),
  'cuteFont': GoogleFonts.cuteFont(),
  'cutive': GoogleFonts.cutive(),
  'cutiveMono': GoogleFonts.cutiveMono(),
  'dMSans': GoogleFonts.dMSans(),
  'dMSerifDisplay': GoogleFonts.dMSerifDisplay(),
  'dMSerifText': GoogleFonts.dMSerifText(),
  'damion': GoogleFonts.damion(),
  'dancingScript': GoogleFonts.dancingScript(),
  'dangrek': GoogleFonts.dangrek(),
  'darkerGrotesque': GoogleFonts.darkerGrotesque(),
  'davidLibre': GoogleFonts.davidLibre(),
  'dawningofaNewDay': GoogleFonts.dawningofaNewDay(),
  'daysOne': GoogleFonts.daysOne(),
  'dekko': GoogleFonts.dekko(),
  'delius': GoogleFonts.delius(),
  'deliusSwashCaps': GoogleFonts.deliusSwashCaps(),
  'deliusUnicase': GoogleFonts.deliusUnicase(),
  'dellaRespira': GoogleFonts.dellaRespira(),
  'denkOne': GoogleFonts.denkOne(),
  'devonshire': GoogleFonts.devonshire(),
  'dhurjati': GoogleFonts.dhurjati(),
  'didactGothic': GoogleFonts.didactGothic(),
  'diplomata': GoogleFonts.diplomata(),
  'diplomataSC': GoogleFonts.diplomataSC(),
  'doHyeon': GoogleFonts.doHyeon(),
  'dokdo': GoogleFonts.dokdo(),
  'domine': GoogleFonts.domine(),
  'donegalOne': GoogleFonts.donegalOne(),
  'doppioOne': GoogleFonts.doppioOne(),
  'dorsa': GoogleFonts.dorsa(),
  'dosis': GoogleFonts.dosis(),
  'drSugiyama': GoogleFonts.drSugiyama(),
  'duruSans': GoogleFonts.duruSans(),
  'dynalight': GoogleFonts.dynalight(),
  'eBGaramond': GoogleFonts.eBGaramond(),
  'eagleLake': GoogleFonts.eagleLake(),
  'eastSeaDokdo': GoogleFonts.eastSeaDokdo(),
  'eater': GoogleFonts.eater(),
  'economica': GoogleFonts.economica(),
  'eczar': GoogleFonts.eczar(),
  'elMessiri': GoogleFonts.elMessiri(),
  'electrolize': GoogleFonts.electrolize(),
  'elsie': GoogleFonts.elsie(),
  'elsieSwashCaps': GoogleFonts.elsieSwashCaps(),
  'emblemaOne': GoogleFonts.emblemaOne(),
  'emilysCandy': GoogleFonts.emilysCandy(),
  'encodeSans': GoogleFonts.encodeSans(),
  'encodeSansCondensed': GoogleFonts.encodeSansCondensed(),
  'encodeSansExpanded': GoogleFonts.encodeSansExpanded(),
  'encodeSansSemiCondensed': GoogleFonts.encodeSansSemiCondensed(),
  'encodeSansSemiExpanded': GoogleFonts.encodeSansSemiExpanded(),
  'engagement': GoogleFonts.engagement(),
  'englebert': GoogleFonts.englebert(),
  'enriqueta': GoogleFonts.enriqueta(),
  'ericaOne': GoogleFonts.ericaOne(),
  'esteban': GoogleFonts.esteban(),
  'euphoriaScript': GoogleFonts.euphoriaScript(),
  'ewert': GoogleFonts.ewert(),
  'exo': GoogleFonts.exo(),
  'exo2': GoogleFonts.exo2(),
  'expletusSans': GoogleFonts.expletusSans(),
  'fahkwang': GoogleFonts.fahkwang(),
  'fanwoodText': GoogleFonts.fanwoodText(),
  'farro': GoogleFonts.farro(),
  'farsan': GoogleFonts.farsan(),
  'fascinate': GoogleFonts.fascinate(),
  'fascinateInline': GoogleFonts.fascinateInline(),
  'fasterOne': GoogleFonts.fasterOne(),
  'fasthand': GoogleFonts.fasthand(),
  'faunaOne': GoogleFonts.faunaOne(),
  'faustina': GoogleFonts.faustina(),
  'federant': GoogleFonts.federant(),
  'federo': GoogleFonts.federo(),
  'felipa': GoogleFonts.felipa(),
  'fenix': GoogleFonts.fenix(),
  'fingerPaint': GoogleFonts.fingerPaint(),
  'firaCode': GoogleFonts.firaCode(),
  'firaMono': GoogleFonts.firaMono(),
  'firaSans': GoogleFonts.firaSans(),
  'firaSansCondensed': GoogleFonts.firaSansCondensed(),
  'firaSansExtraCondensed': GoogleFonts.firaSansExtraCondensed(),
  'fjallaOne': GoogleFonts.fjallaOne(),
  'fjordOne': GoogleFonts.fjordOne(),
  'flamenco': GoogleFonts.flamenco(),
  'flavors': GoogleFonts.flavors(),
  'fondamento': GoogleFonts.fondamento(),
  'fontdinerSwanky': GoogleFonts.fontdinerSwanky(),
  'forum': GoogleFonts.forum(),
  'francoisOne': GoogleFonts.francoisOne(),
  'frankRuhlLibre': GoogleFonts.frankRuhlLibre(),
  'freckleFace': GoogleFonts.freckleFace(),
  'frederickatheGreat': GoogleFonts.frederickatheGreat(),
  'fredokaOne': GoogleFonts.fredokaOne(),
  'freehand': GoogleFonts.freehand(),
  'fresca': GoogleFonts.fresca(),
  'frijole': GoogleFonts.frijole(),
  'fruktur': GoogleFonts.fruktur(),
  'fugazOne': GoogleFonts.fugazOne(),
  'gFSDidot': GoogleFonts.gFSDidot(),
  'gFSNeohellenic': GoogleFonts.gFSNeohellenic(),
  'gabriela': GoogleFonts.gabriela(),
  'gaegu': GoogleFonts.gaegu(),
  'gafata': GoogleFonts.gafata(),
  'galada': GoogleFonts.galada(),
  'galdeano': GoogleFonts.galdeano(),
  'galindo': GoogleFonts.galindo(),
  'gamjaFlower': GoogleFonts.gamjaFlower(),
  'gayathri': GoogleFonts.gayathri(),
  'gelasio': GoogleFonts.gelasio(),
  'gentiumBasic': GoogleFonts.gentiumBasic(),
  'gentiumBookBasic': GoogleFonts.gentiumBookBasic(),
  'geo': GoogleFonts.geo(),
  'geostar': GoogleFonts.geostar(),
  'geostarFill': GoogleFonts.geostarFill(),
  'germaniaOne': GoogleFonts.germaniaOne(),
  'gidugu': GoogleFonts.gidugu(),
  'gildaDisplay': GoogleFonts.gildaDisplay(),
  'girassol': GoogleFonts.girassol(),
  'giveYouGlory': GoogleFonts.giveYouGlory(),
  'glassAntiqua': GoogleFonts.glassAntiqua(),
  'glegoo': GoogleFonts.glegoo(),
  'gloriaHallelujah': GoogleFonts.gloriaHallelujah(),
  'goblinOne': GoogleFonts.goblinOne(),
  'gochiHand': GoogleFonts.gochiHand(),
  'gorditas': GoogleFonts.gorditas(),
  'gothicA1': GoogleFonts.gothicA1(),
  'goudyBookletter1911': GoogleFonts.goudyBookletter1911(),
  'graduate': GoogleFonts.graduate(),
  'grandHotel': GoogleFonts.grandHotel(),
  'gravitasOne': GoogleFonts.gravitasOne(),
  'greatVibes': GoogleFonts.greatVibes(),
  'grenze': GoogleFonts.grenze(),
  'griffy': GoogleFonts.griffy(),
  'gruppo': GoogleFonts.gruppo(),
  'gudea': GoogleFonts.gudea(),
  'gugi': GoogleFonts.gugi(),
  'gupter': GoogleFonts.gupter(),
  'gurajada': GoogleFonts.gurajada(),
  'habibi': GoogleFonts.habibi(),
  'halant': GoogleFonts.halant(),
  'hammersmithOne': GoogleFonts.hammersmithOne(),
  'hanalei': GoogleFonts.hanalei(),
  'hanaleiFill': GoogleFonts.hanaleiFill(),
  'handlee': GoogleFonts.handlee(),
  'hanuman': GoogleFonts.hanuman(),
  'happyMonkey': GoogleFonts.happyMonkey(),
  'harmattan': GoogleFonts.harmattan(),
  'headlandOne': GoogleFonts.headlandOne(),
  'heebo': GoogleFonts.heebo(),
  'hennyPenny': GoogleFonts.hennyPenny(),
  'heptaSlab': GoogleFonts.heptaSlab(),
  'herrVonMuellerhoff': GoogleFonts.herrVonMuellerhoff(),
  'hiMelody': GoogleFonts.hiMelody(),
  'hind': GoogleFonts.hind(),
  'hindGuntur': GoogleFonts.hindGuntur(),
  'hindMadurai': GoogleFonts.hindMadurai(),
  'hindSiliguri': GoogleFonts.hindSiliguri(),
  'hindVadodara': GoogleFonts.hindVadodara(),
  'holtwoodOneSC': GoogleFonts.holtwoodOneSC(),
  'homemadeApple': GoogleFonts.homemadeApple(),
  'homenaje': GoogleFonts.homenaje(),
  'iBMPlexMono': GoogleFonts.iBMPlexMono(),
  'iBMPlexSans': GoogleFonts.iBMPlexSans(),
  'iBMPlexSansCondensed': GoogleFonts.iBMPlexSansCondensed(),
  'iBMPlexSerif': GoogleFonts.iBMPlexSerif(),
  'iMFellDWPica': GoogleFonts.iMFellDWPica(),
  'iMFellDWPicaSC': GoogleFonts.iMFellDWPicaSC(),
  'iMFellDoublePica': GoogleFonts.iMFellDoublePica(),
  'iMFellDoublePicaSC': GoogleFonts.iMFellDoublePicaSC(),
  'iMFellEnglish': GoogleFonts.iMFellEnglish(),
  'iMFellEnglishSC': GoogleFonts.iMFellEnglishSC(),
  'iMFellFrenchCanon': GoogleFonts.iMFellFrenchCanon(),
  'iMFellFrenchCanonSC': GoogleFonts.iMFellFrenchCanonSC(),
  'iMFellGreatPrimer': GoogleFonts.iMFellGreatPrimer(),
  'iMFellGreatPrimerSC': GoogleFonts.iMFellGreatPrimerSC(),
  'ibarraRealNova': GoogleFonts.ibarraRealNova(),
  'iceberg': GoogleFonts.iceberg(),
  'iceland': GoogleFonts.iceland(),
  'imprima': GoogleFonts.imprima(),
  'inconsolata': GoogleFonts.inconsolata(),
  'inder': GoogleFonts.inder(),
  'indieFlower': GoogleFonts.indieFlower(),
  'inika': GoogleFonts.inika(),
  'inknutAntiqua': GoogleFonts.inknutAntiqua(),
  'inriaSerif': GoogleFonts.inriaSerif(),
  'irishGrover': GoogleFonts.irishGrover(),
  'istokWeb': GoogleFonts.istokWeb(),
  'italiana': GoogleFonts.italiana(),
  'italianno': GoogleFonts.italianno(),
  'itim': GoogleFonts.itim(),
  'jacquesFrancois': GoogleFonts.jacquesFrancois(),
  'jacquesFrancoisShadow': GoogleFonts.jacquesFrancoisShadow(),
  'jaldi': GoogleFonts.jaldi(),
  'jimNightshade': GoogleFonts.jimNightshade(),
  'jockeyOne': GoogleFonts.jockeyOne(),
  'jollyLodger': GoogleFonts.jollyLodger(),
  'jomhuria': GoogleFonts.jomhuria(),
  'jomolhari': GoogleFonts.jomolhari(),
  'josefinSans': GoogleFonts.josefinSans(),
  'josefinSlab': GoogleFonts.josefinSlab(),
  'jotiOne': GoogleFonts.jotiOne(),
  'jua': GoogleFonts.jua(),
  'judson': GoogleFonts.judson(),
  'julee': GoogleFonts.julee(),
  'juliusSansOne': GoogleFonts.juliusSansOne(),
  'junge': GoogleFonts.junge(),
  'jura': GoogleFonts.jura(),
  'justAnotherHand': GoogleFonts.justAnotherHand(),
  'justMeAgainDownHere': GoogleFonts.justMeAgainDownHere(),
  'k2D': GoogleFonts.k2D(),
  'kadwa': GoogleFonts.kadwa(),
  'kalam': GoogleFonts.kalam(),
  'kameron': GoogleFonts.kameron(),
  'kanit': GoogleFonts.kanit(),
  'kantumruy': GoogleFonts.kantumruy(),
  'karla': GoogleFonts.karla(),
  'karma': GoogleFonts.karma(),
  'katibeh': GoogleFonts.katibeh(),
  'kaushanScript': GoogleFonts.kaushanScript(),
  'kavivanar': GoogleFonts.kavivanar(),
  'kavoon': GoogleFonts.kavoon(),
  'kdamThmor': GoogleFonts.kdamThmor(),
  'keaniaOne': GoogleFonts.keaniaOne(),
  'kellySlab': GoogleFonts.kellySlab(),
  'kenia': GoogleFonts.kenia(),
  'khand': GoogleFonts.khand(),
  'khmer': GoogleFonts.khmer(),
  'khula': GoogleFonts.khula(),
  'kirangHaerang': GoogleFonts.kirangHaerang(),
  'kiteOne': GoogleFonts.kiteOne(),
  'knewave': GoogleFonts.knewave(),
  'koHo': GoogleFonts.koHo(),
  'kodchasan': GoogleFonts.kodchasan(),
  'kosugi': GoogleFonts.kosugi(),
  'kosugiMaru': GoogleFonts.kosugiMaru(),
  'kottaOne': GoogleFonts.kottaOne(),
  'koulen': GoogleFonts.koulen(),
  'kranky': GoogleFonts.kranky(),
  'kreon': GoogleFonts.kreon(),
  'kristi': GoogleFonts.kristi(),
  'kronaOne': GoogleFonts.kronaOne(),
  'krub': GoogleFonts.krub(),
  'kulimPark': GoogleFonts.kulimPark(),
  'kumarOne': GoogleFonts.kumarOne(),
  'kumarOneOutline': GoogleFonts.kumarOneOutline(),
  'kurale': GoogleFonts.kurale(),
  'laBelleAurore': GoogleFonts.laBelleAurore(),
  'lacquer': GoogleFonts.lacquer(),
  'laila': GoogleFonts.laila(),
  'lakkiReddy': GoogleFonts.lakkiReddy(),
  'lalezar': GoogleFonts.lalezar(),
  'lancelot': GoogleFonts.lancelot(),
  'lateef': GoogleFonts.lateef(),
  'lato': GoogleFonts.lato(),
  'leagueScript': GoogleFonts.leagueScript(),
  'leckerliOne': GoogleFonts.leckerliOne(),
  'ledger': GoogleFonts.ledger(),
  'lekton': GoogleFonts.lekton(),
  'lemon': GoogleFonts.lemon(),
  'lemonada': GoogleFonts.lemonada(),
  'lexendDeca': GoogleFonts.lexendDeca(),
  'lexendExa': GoogleFonts.lexendExa(),
  'lexendGiga': GoogleFonts.lexendGiga(),
  'lexendMega': GoogleFonts.lexendMega(),
  'lexendPeta': GoogleFonts.lexendPeta(),
  'lexendTera': GoogleFonts.lexendTera(),
  'lexendZetta': GoogleFonts.lexendZetta(),
  'libreBarcode128': GoogleFonts.libreBarcode128(),
  'libreBarcode128Text': GoogleFonts.libreBarcode128Text(),
  'libreBarcode39': GoogleFonts.libreBarcode39(),
  'libreBarcode39Extended': GoogleFonts.libreBarcode39Extended(),
  'libreBarcode39ExtendedText': GoogleFonts.libreBarcode39ExtendedText(),
  'libreBarcode39Text': GoogleFonts.libreBarcode39Text(),
  'libreBaskerville': GoogleFonts.libreBaskerville(),
  'libreCaslonDisplay': GoogleFonts.libreCaslonDisplay(),
  'libreCaslonText': GoogleFonts.libreCaslonText(),
  'libreFranklin': GoogleFonts.libreFranklin(),
  'lifeSavers': GoogleFonts.lifeSavers(),
  'lilitaOne': GoogleFonts.lilitaOne(),
  'lilyScriptOne': GoogleFonts.lilyScriptOne(),
  'limelight': GoogleFonts.limelight(),
  'lindenHill': GoogleFonts.lindenHill(),
  'literata': GoogleFonts.literata(),
  'liuJianMaoCao': GoogleFonts.liuJianMaoCao(),
  'livvic': GoogleFonts.livvic(),
  'lobster': GoogleFonts.lobster(),
  'lobsterTwo': GoogleFonts.lobsterTwo(),
  'londrinaOutline': GoogleFonts.londrinaOutline(),
  'londrinaShadow': GoogleFonts.londrinaShadow(),
  'londrinaSketch': GoogleFonts.londrinaSketch(),
  'londrinaSolid': GoogleFonts.londrinaSolid(),
  'longCang': GoogleFonts.longCang(),
  'lora': GoogleFonts.lora(),
  'loveYaLikeASister': GoogleFonts.loveYaLikeASister(),
  'lovedbytheKing': GoogleFonts.lovedbytheKing(),
  'loversQuarrel': GoogleFonts.loversQuarrel(),
  'luckiestGuy': GoogleFonts.luckiestGuy(),
  'lusitana': GoogleFonts.lusitana(),
  'lustria': GoogleFonts.lustria(),
  'mPLUS1p': GoogleFonts.mPLUS1p(),
  'mPLUSRounded1c': GoogleFonts.mPLUSRounded1c(),
  'maShanZheng': GoogleFonts.maShanZheng(),
  'macondo': GoogleFonts.macondo(),
  'macondoSwashCaps': GoogleFonts.macondoSwashCaps(),
  'mada': GoogleFonts.mada(),
  'magra': GoogleFonts.magra(),
  'maidenOrange': GoogleFonts.maidenOrange(),
  'maitree': GoogleFonts.maitree(),
  'majorMonoDisplay': GoogleFonts.majorMonoDisplay(),
  'mako': GoogleFonts.mako(),
  'mali': GoogleFonts.mali(),
  'mallanna': GoogleFonts.mallanna(),
  'mandali': GoogleFonts.mandali(),
  'manjari': GoogleFonts.manjari(),
  'mansalva': GoogleFonts.mansalva(),
  'manuale': GoogleFonts.manuale(),
  'marcellus': GoogleFonts.marcellus(),
  'marcellusSC': GoogleFonts.marcellusSC(),
  'marckScript': GoogleFonts.marckScript(),
  'margarine': GoogleFonts.margarine(),
  'markaziText': GoogleFonts.markaziText(),
  'markoOne': GoogleFonts.markoOne(),
  'marmelad': GoogleFonts.marmelad(),
  'martel': GoogleFonts.martel(),
  'martelSans': GoogleFonts.martelSans(),
  'marvel': GoogleFonts.marvel(),
  'mate': GoogleFonts.mate(),
  'mateSC': GoogleFonts.mateSC(),
  'mavenPro': GoogleFonts.mavenPro(),
  'mcLaren': GoogleFonts.mcLaren(),
  'meddon': GoogleFonts.meddon(),
  'medievalSharp': GoogleFonts.medievalSharp(),
  'medulaOne': GoogleFonts.medulaOne(),
  'meeraInimai': GoogleFonts.meeraInimai(),
  'megrim': GoogleFonts.megrim(),
  'meieScript': GoogleFonts.meieScript(),
  'merienda': GoogleFonts.merienda(),
  'meriendaOne': GoogleFonts.meriendaOne(),
  'merriweather': GoogleFonts.merriweather(),
  'merriweatherSans': GoogleFonts.merriweatherSans(),
  'metal': GoogleFonts.metal(),
  'metalMania': GoogleFonts.metalMania(),
  'metamorphous': GoogleFonts.metamorphous(),
  'metrophobic': GoogleFonts.metrophobic(),
  'michroma': GoogleFonts.michroma(),
  'milonga': GoogleFonts.milonga(),
  'miltonian': GoogleFonts.miltonian(),
  'miltonianTattoo': GoogleFonts.miltonianTattoo(),
  'mina': GoogleFonts.mina(),
  'miniver': GoogleFonts.miniver(),
  'miriamLibre': GoogleFonts.miriamLibre(),
  'mirza': GoogleFonts.mirza(),
  'missFajardose': GoogleFonts.missFajardose(),
  'mitr': GoogleFonts.mitr(),
  'modak': GoogleFonts.modak(),
  'modernAntiqua': GoogleFonts.modernAntiqua(),
  'mogra': GoogleFonts.mogra(),
  'molengo': GoogleFonts.molengo(),
  'molle': GoogleFonts.molle(),
  'monda': GoogleFonts.monda(),
  'monofett': GoogleFonts.monofett(),
  'monoton': GoogleFonts.monoton(),
  'monsieurLaDoulaise': GoogleFonts.monsieurLaDoulaise(),
  'montaga': GoogleFonts.montaga(),
  'montez': GoogleFonts.montez(),
  'montserrat': GoogleFonts.montserrat(),
  'montserratAlternates': GoogleFonts.montserratAlternates(),
  'montserratSubrayada': GoogleFonts.montserratSubrayada(),
  'moul': GoogleFonts.moul(),
  'moulpali': GoogleFonts.moulpali(),
  'mountainsofChristmas': GoogleFonts.mountainsofChristmas(),
  'mouseMemoirs': GoogleFonts.mouseMemoirs(),
  'mrBedfort': GoogleFonts.mrBedfort(),
  'mrDafoe': GoogleFonts.mrDafoe(),
  'mrDeHaviland': GoogleFonts.mrDeHaviland(),
  'mrsSaintDelafield': GoogleFonts.mrsSaintDelafield(),
  'mrsSheppards': GoogleFonts.mrsSheppards(),
  'mukta': GoogleFonts.mukta(),
  'muktaMahee': GoogleFonts.muktaMahee(),
  'muktaMalar': GoogleFonts.muktaMalar(),
  'muktaVaani': GoogleFonts.muktaVaani(),
  'muli': GoogleFonts.muli(),
  'mysteryQuest': GoogleFonts.mysteryQuest(),
  'nTR': GoogleFonts.nTR(),
  'nanumBrushScript': GoogleFonts.nanumBrushScript(),
  'nanumGothic': GoogleFonts.nanumGothic(),
  'nanumGothicCoding': GoogleFonts.nanumGothicCoding(),
  'nanumMyeongjo': GoogleFonts.nanumMyeongjo(),
  'nanumPenScript': GoogleFonts.nanumPenScript(),
  'neucha': GoogleFonts.neucha(),
  'neuton': GoogleFonts.neuton(),
  'newRocker': GoogleFonts.newRocker(),
  'newsCycle': GoogleFonts.newsCycle(),
  'niconne': GoogleFonts.niconne(),
  'niramit': GoogleFonts.niramit(),
  'nixieOne': GoogleFonts.nixieOne(),
  'nobile': GoogleFonts.nobile(),
  'nokora': GoogleFonts.nokora(),
  'norican': GoogleFonts.norican(),
  'nosifer': GoogleFonts.nosifer(),
  'notable': GoogleFonts.notable(),
  'nothingYouCouldDo': GoogleFonts.nothingYouCouldDo(),
  'noticiaText': GoogleFonts.noticiaText(),
  'notoSans': GoogleFonts.notoSans(),
  'notoSansHK': GoogleFonts.notoSansHK(),
  'notoSansJP': GoogleFonts.notoSansJP(),
  'notoSansKR': GoogleFonts.notoSansKR(),
  'notoSansSC': GoogleFonts.notoSansSC(),
  'notoSansTC': GoogleFonts.notoSansTC(),
  'notoSerif': GoogleFonts.notoSerif(),
  'notoSerifJP': GoogleFonts.notoSerifJP(),
  'notoSerifKR': GoogleFonts.notoSerifKR(),
  'notoSerifSC': GoogleFonts.notoSerifSC(),
  'notoSerifTC': GoogleFonts.notoSerifTC(),
  'novaCut': GoogleFonts.novaCut(),
  'novaFlat': GoogleFonts.novaFlat(),
  'novaMono': GoogleFonts.novaMono(),
  'novaOval': GoogleFonts.novaOval(),
  'novaRound': GoogleFonts.novaRound(),
  'novaScript': GoogleFonts.novaScript(),
  'novaSlim': GoogleFonts.novaSlim(),
  'novaSquare': GoogleFonts.novaSquare(),
  'numans': GoogleFonts.numans(),
  'nunito': GoogleFonts.nunito(),
  'nunitoSans': GoogleFonts.nunitoSans(),
  'odibeeSans': GoogleFonts.odibeeSans(),
  'odorMeanChey': GoogleFonts.odorMeanChey(),
  'offside': GoogleFonts.offside(),
  'oldStandardTT': GoogleFonts.oldStandardTT(),
  'oldenburg': GoogleFonts.oldenburg(),
  'oleoScript': GoogleFonts.oleoScript(),
  'oleoScriptSwashCaps': GoogleFonts.oleoScriptSwashCaps(),
  'openSans': GoogleFonts.openSans(),
  'openSansCondensed': GoogleFonts.openSansCondensed(),
  'oranienbaum': GoogleFonts.oranienbaum(),
  'orbitron': GoogleFonts.orbitron(),
  'oregano': GoogleFonts.oregano(),
  'orienta': GoogleFonts.orienta(),
  'originalSurfer': GoogleFonts.originalSurfer(),
  'oswald': GoogleFonts.oswald(),
  'overtheRainbow': GoogleFonts.overtheRainbow(),
  'overlock': GoogleFonts.overlock(),
  'overlockSC': GoogleFonts.overlockSC(),
  'overpass': GoogleFonts.overpass(),
  'overpassMono': GoogleFonts.overpassMono(),
  'ovo': GoogleFonts.ovo(),
  'oxygen': GoogleFonts.oxygen(),
  'oxygenMono': GoogleFonts.oxygenMono(),
  'pTMono': GoogleFonts.pTMono(),
  'pTSans': GoogleFonts.pTSans(),
  'pTSansCaption': GoogleFonts.pTSansCaption(),
  'pTSansNarrow': GoogleFonts.pTSansNarrow(),
  'pTSerif': GoogleFonts.pTSerif(),
  'pTSerifCaption': GoogleFonts.pTSerifCaption(),
  'pacifico': GoogleFonts.pacifico(),
  'padauk': GoogleFonts.padauk(),
  'palanquin': GoogleFonts.palanquin(),
  'palanquinDark': GoogleFonts.palanquinDark(),
  'pangolin': GoogleFonts.pangolin(),
  'paprika': GoogleFonts.paprika(),
  'parisienne': GoogleFonts.parisienne(),
  'passeroOne': GoogleFonts.passeroOne(),
  'passionOne': GoogleFonts.passionOne(),
  'pathwayGothicOne': GoogleFonts.pathwayGothicOne(),
  'patrickHand': GoogleFonts.patrickHand(),
  'patrickHandSC': GoogleFonts.patrickHandSC(),
  'pattaya': GoogleFonts.pattaya(),
  'patuaOne': GoogleFonts.patuaOne(),
  'pavanam': GoogleFonts.pavanam(),
  'paytoneOne': GoogleFonts.paytoneOne(),
  'peddana': GoogleFonts.peddana(),
  'peralta': GoogleFonts.peralta(),
  'permanentMarker': GoogleFonts.permanentMarker(),
  'petitFormalScript': GoogleFonts.petitFormalScript(),
  'petrona': GoogleFonts.petrona(),
  'philosopher': GoogleFonts.philosopher(),
  'piedra': GoogleFonts.piedra(),
  'pinyonScript': GoogleFonts.pinyonScript(),
  'pirataOne': GoogleFonts.pirataOne(),
  'plaster': GoogleFonts.plaster(),
  'play': GoogleFonts.play(),
  'playball': GoogleFonts.playball(),
  'playfairDisplay': GoogleFonts.playfairDisplay(),
  'playfairDisplaySC': GoogleFonts.playfairDisplaySC(),
  'podkova': GoogleFonts.podkova(),
  'poiretOne': GoogleFonts.poiretOne(),
  'pollerOne': GoogleFonts.pollerOne(),
  'poly': GoogleFonts.poly(),
  'pompiere': GoogleFonts.pompiere(),
  'pontanoSans': GoogleFonts.pontanoSans(),
  'poorStory': GoogleFonts.poorStory(),
  'poppins': GoogleFonts.poppins(),
  'portLligatSans': GoogleFonts.portLligatSans(),
  'portLligatSlab': GoogleFonts.portLligatSlab(),
  'pragatiNarrow': GoogleFonts.pragatiNarrow(),
  'prata': GoogleFonts.prata(),
  'preahvihear': GoogleFonts.preahvihear(),
  'pressStart2P': GoogleFonts.pressStart2P(),
  'pridi': GoogleFonts.pridi(),
  'princessSofia': GoogleFonts.princessSofia(),
  'prociono': GoogleFonts.prociono(),
  'prompt': GoogleFonts.prompt(),
  'prostoOne': GoogleFonts.prostoOne(),
  'prozaLibre': GoogleFonts.prozaLibre(),
  'publicSans': GoogleFonts.publicSans(),
  'puritan': GoogleFonts.puritan(),
  'purplePurse': GoogleFonts.purplePurse(),
  'quando': GoogleFonts.quando(),
  'quantico': GoogleFonts.quantico(),
  'quattrocento': GoogleFonts.quattrocento(),
  'quattrocentoSans': GoogleFonts.quattrocentoSans(),
  'questrial': GoogleFonts.questrial(),
  'quicksand': GoogleFonts.quicksand(),
  'quintessential': GoogleFonts.quintessential(),
  'qwigley': GoogleFonts.qwigley(),
  'racingSansOne': GoogleFonts.racingSansOne(),
  'radley': GoogleFonts.radley(),
  'rajdhani': GoogleFonts.rajdhani(),
  'rakkas': GoogleFonts.rakkas(),
  'raleway': GoogleFonts.raleway(),
  'ralewayDots': GoogleFonts.ralewayDots(),
  'ramabhadra': GoogleFonts.ramabhadra(),
  'ramaraja': GoogleFonts.ramaraja(),
  'rambla': GoogleFonts.rambla(),
  'rammettoOne': GoogleFonts.rammettoOne(),
  'ranchers': GoogleFonts.ranchers(),
  'rancho': GoogleFonts.rancho(),
  'ranga': GoogleFonts.ranga(),
  'rasa': GoogleFonts.rasa(),
  'rationale': GoogleFonts.rationale(),
  'raviPrakash': GoogleFonts.raviPrakash(),
  'redHatDisplay': GoogleFonts.redHatDisplay(),
  'redHatText': GoogleFonts.redHatText(),
  'redressed': GoogleFonts.redressed(),
  'reemKufi': GoogleFonts.reemKufi(),
  'reenieBeanie': GoogleFonts.reenieBeanie(),
  'revalia': GoogleFonts.revalia(),
  'rhodiumLibre': GoogleFonts.rhodiumLibre(),
  'ribeye': GoogleFonts.ribeye(),
  'ribeyeMarrow': GoogleFonts.ribeyeMarrow(),
  'righteous': GoogleFonts.righteous(),
  'risque': GoogleFonts.risque(),
  'roboto': GoogleFonts.roboto(),
  'robotoCondensed': GoogleFonts.robotoCondensed(),
  'robotoMono': GoogleFonts.robotoMono(),
  'robotoSlab': GoogleFonts.robotoSlab(),
  'rochester': GoogleFonts.rochester(),
  'rockSalt': GoogleFonts.rockSalt(),
  'rokkitt': GoogleFonts.rokkitt(),
  'romanesco': GoogleFonts.romanesco(),
  'ropaSans': GoogleFonts.ropaSans(),
  'rosario': GoogleFonts.rosario(),
  'rosarivo': GoogleFonts.rosarivo(),
  'rougeScript': GoogleFonts.rougeScript(),
  'rozhaOne': GoogleFonts.rozhaOne(),
  'rubik': GoogleFonts.rubik(),
  'rubikMonoOne': GoogleFonts.rubikMonoOne(),
  'ruda': GoogleFonts.ruda(),
  'rufina': GoogleFonts.rufina(),
  'rugeBoogie': GoogleFonts.rugeBoogie(),
  'ruluko': GoogleFonts.ruluko(),
  'rumRaisin': GoogleFonts.rumRaisin(),
  'ruslanDisplay': GoogleFonts.ruslanDisplay(),
  'russoOne': GoogleFonts.russoOne(),
  'ruthie': GoogleFonts.ruthie(),
  'rye': GoogleFonts.rye(),
  'sacramento': GoogleFonts.sacramento(),
  'sahitya': GoogleFonts.sahitya(),
  'sail': GoogleFonts.sail(),
  'saira': GoogleFonts.saira(),
  'sairaCondensed': GoogleFonts.sairaCondensed(),
  'sairaExtraCondensed': GoogleFonts.sairaExtraCondensed(),
  'sairaSemiCondensed': GoogleFonts.sairaSemiCondensed(),
  'sairaStencilOne': GoogleFonts.sairaStencilOne(),
  'salsa': GoogleFonts.salsa(),
  'sanchez': GoogleFonts.sanchez(),
  'sancreek': GoogleFonts.sancreek(),
  'sansita': GoogleFonts.sansita(),
  'sarabun': GoogleFonts.sarabun(),
  'sarala': GoogleFonts.sarala(),
  'sarina': GoogleFonts.sarina(),
  'sarpanch': GoogleFonts.sarpanch(),
  'satisfy': GoogleFonts.satisfy(),
  'sawarabiGothic': GoogleFonts.sawarabiGothic(),
  'sawarabiMincho': GoogleFonts.sawarabiMincho(),
  'scada': GoogleFonts.scada(),
  'scheherazade': GoogleFonts.scheherazade(),
  'schoolbell': GoogleFonts.schoolbell(),
  'scopeOne': GoogleFonts.scopeOne(),
  'seaweedScript': GoogleFonts.seaweedScript(),
  'secularOne': GoogleFonts.secularOne(),
  'sedgwickAve': GoogleFonts.sedgwickAve(),
  'sedgwickAveDisplay': GoogleFonts.sedgwickAveDisplay(),
  'sevillana': GoogleFonts.sevillana(),
  'seymourOne': GoogleFonts.seymourOne(),
  'shadowsIntoLight': GoogleFonts.shadowsIntoLight(),
  'shadowsIntoLightTwo': GoogleFonts.shadowsIntoLightTwo(),
  'shanti': GoogleFonts.shanti(),
  'share': GoogleFonts.share(),
  'shareTech': GoogleFonts.shareTech(),
  'shareTechMono': GoogleFonts.shareTechMono(),
  'shojumaru': GoogleFonts.shojumaru(),
  'shortStack': GoogleFonts.shortStack(),
  'shrikhand': GoogleFonts.shrikhand(),
  'siemreap': GoogleFonts.siemreap(),
  'sigmarOne': GoogleFonts.sigmarOne(),
  'signika': GoogleFonts.signika(),
  'signikaNegative': GoogleFonts.signikaNegative(),
  'simonetta': GoogleFonts.simonetta(),
  'singleDay': GoogleFonts.singleDay(),
  'sintony': GoogleFonts.sintony(),
  'sirinStencil': GoogleFonts.sirinStencil(),
  'sixCaps': GoogleFonts.sixCaps(),
  'skranji': GoogleFonts.skranji(),
  'slabo13px': GoogleFonts.slabo13px(),
  'slabo27px': GoogleFonts.slabo27px(),
  'slackey': GoogleFonts.slackey(),
  'smokum': GoogleFonts.smokum(),
  'smythe': GoogleFonts.smythe(),
  'sniglet': GoogleFonts.sniglet(),
  'snippet': GoogleFonts.snippet(),
  'snowburstOne': GoogleFonts.snowburstOne(),
  'sofadiOne': GoogleFonts.sofadiOne(),
  'sofia': GoogleFonts.sofia(),
  'solway': GoogleFonts.solway(),
  'songMyung': GoogleFonts.songMyung(),
  'sonsieOne': GoogleFonts.sonsieOne(),
  'sortsMillGoudy': GoogleFonts.sortsMillGoudy(),
  'sourceCodePro': GoogleFonts.sourceCodePro(),
  'sourceSansPro': GoogleFonts.sourceSansPro(),
  'sourceSerifPro': GoogleFonts.sourceSerifPro(),
  'spaceMono': GoogleFonts.spaceMono(),
  'specialElite': GoogleFonts.specialElite(),
  'spectral': GoogleFonts.spectral(),
  'spectralSC': GoogleFonts.spectralSC(),
  'spicyRice': GoogleFonts.spicyRice(),
  'spinnaker': GoogleFonts.spinnaker(),
  'spirax': GoogleFonts.spirax(),
  'squadaOne': GoogleFonts.squadaOne(),
  'sreeKrushnadevaraya': GoogleFonts.sreeKrushnadevaraya(),
  'sriracha': GoogleFonts.sriracha(),
  'srisakdi': GoogleFonts.srisakdi(),
  'staatliches': GoogleFonts.staatliches(),
  'stalemate': GoogleFonts.stalemate(),
  'stalinistOne': GoogleFonts.stalinistOne(),
  'stardosStencil': GoogleFonts.stardosStencil(),
  'stintUltraCondensed': GoogleFonts.stintUltraCondensed(),
  'stintUltraExpanded': GoogleFonts.stintUltraExpanded(),
  'stoke': GoogleFonts.stoke(),
  'strait': GoogleFonts.strait(),
  'stylish': GoogleFonts.stylish(),
  'sueEllenFrancisco': GoogleFonts.sueEllenFrancisco(),
  'suezOne': GoogleFonts.suezOne(),
  'sulphurPoint': GoogleFonts.sulphurPoint(),
  'sumana': GoogleFonts.sumana(),
  'sunflower': GoogleFonts.sunflower(),
  'sunshiney': GoogleFonts.sunshiney(),
  'supermercadoOne': GoogleFonts.supermercadoOne(),
  'sura': GoogleFonts.sura(),
  'suranna': GoogleFonts.suranna(),
  'suravaram': GoogleFonts.suravaram(),
  'suwannaphum': GoogleFonts.suwannaphum(),
  'swankyandMooMoo': GoogleFonts.swankyandMooMoo(),
  'syncopate': GoogleFonts.syncopate(),
  'tajawal': GoogleFonts.tajawal(),
  'tangerine': GoogleFonts.tangerine(),
  'taprom': GoogleFonts.taprom(),
  'tauri': GoogleFonts.tauri(),
  'taviraj': GoogleFonts.taviraj(),
  'teko': GoogleFonts.teko(),
  'telex': GoogleFonts.telex(),
  'tenaliRamakrishna': GoogleFonts.tenaliRamakrishna(),
  'tenorSans': GoogleFonts.tenorSans(),
  'textMeOne': GoogleFonts.textMeOne(),
  'thasadith': GoogleFonts.thasadith(),
  'theGirlNextDoor': GoogleFonts.theGirlNextDoor(),
  'tienne': GoogleFonts.tienne(),
  'tillana': GoogleFonts.tillana(),
  'timmana': GoogleFonts.timmana(),
  'tinos': GoogleFonts.tinos(),
  'titanOne': GoogleFonts.titanOne(),
  'titilliumWeb': GoogleFonts.titilliumWeb(),
  'tomorrow': GoogleFonts.tomorrow(),
  'tradeWinds': GoogleFonts.tradeWinds(),
  'trirong': GoogleFonts.trirong(),
  'trocchi': GoogleFonts.trocchi(),
  'trochut': GoogleFonts.trochut(),
  'trykker': GoogleFonts.trykker(),
  'tulpenOne': GoogleFonts.tulpenOne(),
  'turretRoad': GoogleFonts.turretRoad(),
  'ubuntu': GoogleFonts.ubuntu(),
  'ubuntuCondensed': GoogleFonts.ubuntuCondensed(),
  'ubuntuMono': GoogleFonts.ubuntuMono(),
  'ultra': GoogleFonts.ultra(),
  'uncialAntiqua': GoogleFonts.uncialAntiqua(),
  'underdog': GoogleFonts.underdog(),
  'unicaOne': GoogleFonts.unicaOne(),
  'unifrakturCook': GoogleFonts.unifrakturCook(),
  'unifrakturMaguntia': GoogleFonts.unifrakturMaguntia(),
  'unkempt': GoogleFonts.unkempt(),
  'unlock': GoogleFonts.unlock(),
  'unna': GoogleFonts.unna(),
  'vT323': GoogleFonts.vT323(),
  'vampiroOne': GoogleFonts.vampiroOne(),
  'varela': GoogleFonts.varela(),
  'varelaRound': GoogleFonts.varelaRound(),
  'vastShadow': GoogleFonts.vastShadow(),
  'vesperLibre': GoogleFonts.vesperLibre(),
  'vibes': GoogleFonts.vibes(),
  'vibur': GoogleFonts.vibur(),
  'vidaloka': GoogleFonts.vidaloka(),
  'viga': GoogleFonts.viga(),
  'voces': GoogleFonts.voces(),
  'volkhov': GoogleFonts.volkhov(),
  'vollkorn': GoogleFonts.vollkorn(),
  'vollkornSC': GoogleFonts.vollkornSC(),
  'voltaire': GoogleFonts.voltaire(),
  'waitingfortheSunrise': GoogleFonts.waitingfortheSunrise(),
  'wallpoet': GoogleFonts.wallpoet(),
  'walterTurncoat': GoogleFonts.walterTurncoat(),
  'warnes': GoogleFonts.warnes(),
  'wellfleet': GoogleFonts.wellfleet(),
  'wendyOne': GoogleFonts.wendyOne(),
  'wireOne': GoogleFonts.wireOne(),
  'workSans': GoogleFonts.workSans(),
  'yanoneKaffeesatz': GoogleFonts.yanoneKaffeesatz(),
  'yantramanav': GoogleFonts.yantramanav(),
  'yatraOne': GoogleFonts.yatraOne(),
  'yellowtail': GoogleFonts.yellowtail(),
  'yeonSung': GoogleFonts.yeonSung(),
  'yesevaOne': GoogleFonts.yesevaOne(),
  'yesteryear': GoogleFonts.yesteryear(),
  'yrsa': GoogleFonts.yrsa(),
  'zCOOLKuaiLe': GoogleFonts.zCOOLKuaiLe(),
  'zCOOLQingKeHuangYou': GoogleFonts.zCOOLQingKeHuangYou(),
  'zCOOLXiaoWei': GoogleFonts.zCOOLXiaoWei(),
  'zeyada': GoogleFonts.zeyada(),
  'zhiMangXing': GoogleFonts.zhiMangXing(),
  'zillaSlab': GoogleFonts.zillaSlab(),
  'zillaSlabHighlight': GoogleFonts.zillaSlabHighlight(),
};

String addLineNumbersTo(String text) {
  final lines = text.split('\n');
  for (int i = 0; i < lines.length; i++) {
    lines[i] = (i + 1).toString() + ' ' + lines[i];
  }
  return lines.join('\n');
}
